// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SnapCash.Infrastructure.Data;

#nullable disable

namespace SnapCash.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250427170837_UpdateDataBase")]
    partial class UpdateDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("SnapCash.Domain.Entities.Register", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nomeCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("saldo")
                        .HasColumnType("TEXT");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Registers");
                });

            modelBuilder.Entity("SnapCash.Domain.Entities.Transfer", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("payee")
                        .HasColumnType("INTEGER");

                    b.Property<int>("payer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("registerid")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("valor")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("registerid");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("SnapCash.Domain.Entities.Transfer", b =>
                {
                    b.HasOne("SnapCash.Domain.Entities.Register", "register")
                        .WithMany()
                        .HasForeignKey("registerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("register");
                });
#pragma warning restore 612, 618
        }
    }
}
