// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SnapCash.Infrastructure.Data;

#nullable disable

namespace SnapCash.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("SnapCash.Domain.Entities.Register", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Registers", (string)null);
                });

            modelBuilder.Entity("SnapCash.Domain.Entities.Transfer", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("payeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("payerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("valor")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("payeeId");

                    b.HasIndex("payerId");

                    b.ToTable("Transfers", (string)null);
                });

            modelBuilder.Entity("SnapCash.Domain.Entities.Transfer", b =>
                {
                    b.HasOne("SnapCash.Domain.Entities.Register", "payee")
                        .WithMany()
                        .HasForeignKey("payeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnapCash.Domain.Entities.Register", "payer")
                        .WithMany()
                        .HasForeignKey("payerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("payee");

                    b.Navigation("payer");
                });
#pragma warning restore 612, 618
        }
    }
}
